name: Docker Build & Publish Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Crear archivo .env con los secrets
      - name: Create .env file
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" >> .env
          echo ".env file creado con API_URL y MAPBOX_TOKEN"

      # 3. Login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build de la imagen Docker usando Dockerfile del frontend
      - name: Build Docker Image
        run: docker build -f NatureAPI-Frontend/Dockerfile -t mariguapo/nature-frontend:${{ github.sha }} .

      # 5. Tag como latest
      - name: Tag Latest
        run: docker tag mariguapo/nature-frontend:${{ github.sha }} mariguapo/nature-frontend:latest

      # 6. Push de la imagen a Docker Hub
      - name: Push Docker Image
        run: |
          docker push mariguapo/nature-frontend:${{ github.sha }}
          docker push mariguapo/nature-frontend:latest
